// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXm9BjzFsAsedwBJUTs9muLUN0AyEvpyA',
    appId: '1:123070157176:web:7657a8f1e0c00c2a16f88d',
    messagingSenderId: '123070157176',
    projectId: 'cophat-25881',
    authDomain: 'cophat-25881.firebaseapp.com',
    storageBucket: 'cophat-25881.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuyrh1wBPBmdlKuzJudJ-KLK8JorkWRn0',
    appId: '1:123070157176:android:a0857331823fe08716f88d',
    messagingSenderId: '123070157176',
    projectId: 'cophat-25881',
    storageBucket: 'cophat-25881.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMtJ6SoMrcVgKWdMRKTsoPNYZMWqlC5_E',
    appId: '1:123070157176:ios:7f87f9b6213743cd16f88d',
    messagingSenderId: '123070157176',
    projectId: 'cophat-25881',
    storageBucket: 'cophat-25881.appspot.com',
    iosBundleId: 'br.com.ruyano.cophat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMtJ6SoMrcVgKWdMRKTsoPNYZMWqlC5_E',
    appId: '1:123070157176:ios:7f87f9b6213743cd16f88d',
    messagingSenderId: '123070157176',
    projectId: 'cophat-25881',
    storageBucket: 'cophat-25881.appspot.com',
    iosBundleId: 'br.com.ruyano.cophat',
  );
}
